<?php
echo "<h2>PHP File Functions</h2>";
$file = "amma.txt";
echo "WRITE"."<br>";
$f = fopen($file, "w");
fwrite($f, "Hello PHP File Handling\n");
fclose($f);
echo "File written successfully.<br>";
echo "READ"."<br>";
$f = fopen($file, "r");
echo "File Content: " . fread($f, filesize($file)) . "<br>";
fclose($f);
echo "file_content"."<br>";
echo "Using file_get_contents(): " . file_get_contents($file) . "<br>";
file_put_contents("demo.txt", "This is demo file");
echo "demo.txt created.<br>";
print_r(file($file));
echo "<br>";
echo "file_information"."<br>";
echo "Exists: " . file_exists($file) . "<br>";
echo "Size: " . filesize($file) . " bytes<br>";
echo "Type: " . filetype($file) . "<br>";
echo "Last Access: " . date("d-m-Y H:i:s", fileatime($file)) . "<br>";
echo "Last Modified: " . date("d-m-Y H:i:s", filemtime($file)) . "<br>";
echo "Permissions: " . fileperms($file) . "<br>";
echo "Owner: " . fileowner($file) . "<br>";
echo "Group: " . filegroup($file) . "<br>";
echo "Inode: " . fileinode($file) . "<br>";
copy($file, "copy.txt");
echo "File copied.<br>";
rename("copy.txt", "renamed.txt");
echo "File renamed.<br>";
unlink("renamed.txt");
echo "File deleted.<br>";
mkdir("myfolder");
echo "Folder created.<br>";
rmdir("myfolder");
echo "Folder removed.<br>";
echo "is_file: " . is_file($file) . "<br>";
echo "is_dir: " . is_dir("uploads") . "<br>";
echo "<h3>Directory Files:</h3>";
print_r(scandir(".")); 
echo "<br>Current Dir: " . getcwd();
echo "file lock"."<br>";
$f = fopen($file, "r+");
flock($f, LOCK_EX);
fwrite($f, "\nLocked Write");
flock($f, LOCK_UN);
fclose($f);
echo "<br>File locked and written safely.";
$file = "amma.txt";
$f = fopen($file, "r");
fclose($f);
$f = fopen($file, "w");
fwrite($f, "Write Mode\n");
fclose($f);
$f = fopen($file, "a");
fwrite($f, "Append Mode\n");
fclose($f);
$f = fopen("amma.txt", "w");
fwrite($f, "Created using w mode");
fclose($f);
$f = fopen($file, "r+");
fwrite($f, "r+ Mode\n");
fclose($f);
$f = fopen($file, "w+");
fwrite($f, "w+ Mode\n");
fclose($f);
$f = fopen($file, "a+");
fwrite($f, "a+ Mode\n");
fclose($f);
$f = fopen("amma.txt", "w+");
fwrite($f, "w+ Mode");
fclose($f);
echo "All file modes executed successfully!";
?>